version: "3.8"

services:
    web:
        image: fedha
        build: ./
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres:13
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=staphone
            - POSTGRES_DB=fedha

volumes:
    postgres_data:
