# Generated by Django 4.0 on 2022-12-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_registration_first_name_registration_last_name'),
        ('blogs', '0004_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.registration'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.registration'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
