# Generated by Django 4.0 on 2022-12-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
