# Generated by Django 4.0 on 2022-08-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_application', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(help_text='Amount you want to repay.')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanapplication')),
                ('payee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.registration')),
            ],
        ),
    ]
