# Generated by Django 4.0 on 2022-08-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanrepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='date_of_application',
            new_name='date_of_repayment',
        ),
    ]
