# Generated by Django 4.0 on 2022-12-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_rename_loan_type_loanrepayment_loan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
