# Generated by Django 4.0 on 2022-12-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanapplication_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='payee_name',
            new_name='payee_id',
        ),
    ]
