# Generated by Django 4.0 on 2022-12-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loanrepayment_loan_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount',
            field=models.FloatField(help_text='Amount you want to repay.'),
        ),
    ]
