# Generated by Django 4.0 on 2022-12-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
